# Generated by Django 5.1 on 2024-08-22 01:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('level', models.FloatField(verbose_name='Water Level')),
                ('report_date', models.DateField(verbose_name='Report Date')),
            ],
        ),
    ]
