# Generated by Django 5.1 on 2024-08-22 01:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_entity_id', models.UUIDField(verbose_name='Related Entity ID')),
                ('related_entity_service', models.CharField(max_length=100, verbose_name='Related Entity Service')),
                ('metric_name', models.CharField(max_length=255, verbose_name='Metric Name')),
                ('metric_value', models.FloatField(verbose_name='Metric Value')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
    ]
